[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
ffi-support = "0.4.0"

[build-dependencies]
cbindgen = "0.13.1"
